title: SCHH Boar & RV Website

description: >
  Website This is the initial shot at the SCHH Boat and RV Club Website

author:
  name: Tom Dodrill
  email: tom.dodrill@gmail.com

nav_pages:
  - about.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
